version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE : achatdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

    ports:
      - "3306:3306"
    networks:
      - net

  server:
    depends_on:
      - db
    image: mdaziz/oueslati-achat:1.1.1
    container_name: achatserver
   # restart: on-failure
    ports:
      - "8089:8089"
    environment:

      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      

    stdin_open: true
    tty: true
    networks:
      - net
  client:
    image: angular-oueslati:1.0
    container_name: angular1
    ports:
      - "4200:4200"
networks:
  net:

