version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - 3306:3306
    networks:
      - net

  server:
    depends_on:
      - mysql
    image: mdaziz/oueslati-achat:latest
    container_name: achatserver1
   # restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC",        "spring.datasource.username" : "root",
        "spring.datasource.username" : "root",
        "spring.datasource.password" :  "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

    stdin_open: true
    tty: true
    networks:
      - net
  client:
    image: angular-oueslati:1.0
    container_name: angular1
    ports:
      - "4200:4200"
networks:
  net:

